apiVersion: v1
kind: Secret
metadata:
  name: fuel-monitoring-secret
  namespace: fuel-monitoring
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:password@postgres:5432/fuel_monitoring_db"