apiVersion: v1
kind: Secret
metadata:
  name: fuel-monitoring-secret
  namespace: fuel-monitoring
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "fuel_monitoring_db"